In [1]:
import pandas as pd
dataset= pd.read_csv("classifier_data_0.csv")
dataset.drop(['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9'], axis=1, inplace = True)
dataset.head()

description
0  Product Version      : <see about:version>URLs...
1  Product Version      : 0.2.149.27 (1583)URLs (...
2  Product Version      : chrome beta 1URLs (if a...
3  Product Version      : 0.2.149.27 (1583)URLs (...
4  Product Version      : 0.2.149.27URLs (if appl...

In [2]:
len(dataset)
print(dataset.shape)

(5000, 1)


In [3]:
dataset['description'][0]

"Product Version      : <see about:version>URLs (if applicable) :0.2.149.27Other browsers tested: Firefox / IEAdd OK or FAIL after other browsers where you have tested this issue:Safari 3:    Firefox 3: OK         IE 7:OKWhat steps will reproduce the problem?1. Open any webpage on compaq 6715s running vista.2. Try scrolling with the touchpad3. Scrolling down will work , but up will not.What is the expected result?The page to scroll up.What happens instead?The page doesn't move.Please provide any additional information below. Attach a screenshot if possible.Only a minor bug. "

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_df=0.95,min_df=2,stop_words="english")
dtm= cv.fit_transform(dataset['description'])
dtm

<5000x12306 sparse matrix of type '<class 'numpy.int64'>'
	with 200567 stored elements in Compressed Sparse Row format>

In [5]:
from sklearn.decomposition import LatentDirichletAllocation
LDA = LatentDirichletAllocation(n_components=150, random_state=42)
LDA.fit(dtm)

LatentDirichletAllocation(n_components=150, random_state=42)

In [6]:
len(cv.get_feature_names())

12306

In [7]:
type(cv.get_feature_names())

list

In [8]:
import random
for i in range(10):
    random_word_id=random.randint(0,12306)
    print(cv.get_feature_names()[random_word_id])

lynx
esp
trailing
2677
simplehttpserver
allocator
dave
tell
forbids
95


In [9]:
LDA.components_

array([[0.00666667, 0.00666667, 0.00666667, ..., 0.00666667, 0.00666667,
        0.00666667],
       [0.00666667, 0.00666667, 0.00666667, ..., 0.00666667, 0.00666667,
        0.00666667],
       [0.00666667, 0.00666667, 0.00666667, ..., 0.00666667, 0.00666667,
        0.00666667],
       ...,
       [0.00666667, 0.00666667, 0.00666667, ..., 0.00666667, 0.00666667,
        0.00666667],
       [0.00666667, 2.00666667, 0.00666667, ..., 0.00666667, 0.00666667,
        2.00666667],
       [0.00666667, 0.00666667, 0.00666667, ..., 0.00666667, 0.00666667,
        0.00666667]])

In [10]:
single_topic=LDA.components_[0]
single_topic.argsort()

array([    0,  8130,  8131, ...,  7148, 10501,  3498])

In [11]:
#least representative
single_topic[10666]
#most representative
single_topic[3498]
top_word_indices= single_topic.argsort()[-10:]

In [12]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

build
browser
self
functional
py
file
test
line
src
chrome


In [13]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['git', 'notifications', 'pyautolib', 'volumes', 'pyauto', 'build', 'browser', 'self', 'functional', 'py', 'file', 'test', 'line', 'src', 'chrome']


THE TOP 15 WORDS FOR TOPIC #1
['sync', 'sr', 'cc', 'extension', 'build', 'pair', 'internal', 'uilder', 'src', 'protobuf', 'const', 'google', 'int', 'syncable', 'std']


THE TOP 15 WORDS FOR TOPIC #2
['request', 'id', '32', 'console', 'mov', 'click', '150', 'bytes', '192', '168', 'installer', 'chrome', 'time', 'push', 'setup']


THE TOP 15 WORDS FOR TOPIC #3
['right', 'make', 'bug', 'doing', 'work', 'probably', 'http', 'display', 'using', 'away', 'compositor', 'windows', '3d', 'instead', 'page']


THE TOP 15 WORDS FOR TOPIC #4
['src', 'base', 'bindings', 'core', 'cc', 'content', 'const', 'cpp', 'wtf', 'content_browsertests', 'source', 'webcore', 'third_party', 'webkit', 'v8']


THE TOP 15 WORDS FOR TOPIC #5
['provide', 'information', 'chrome', 'additional', 'menu', 'drop', 'print', 'output', 'dialog', 'steps',

['send', 'pseudomodem', 'vm', 'don', 'connect', 'wrapper', 'fail', 'passed', 'kvm', 'combined', 'black', 'color', 'theme', 'control', 'tmp']


THE TOP 15 WORDS FOR TOPIC #48
['activated', 'controls', 'wheel', 'kernel', 'visited', 'clicked', 'chrome', 'copy', 'item', 'mouse', 'applet', 'button', 'menu', 'java', 'dropdown']


THE TOP 15 WORDS FOR TOPIC #49
['base', 'const', 'cc', 'gtest', 'net', 'ild', 'long', 'short', 'buildd', '12', 'security', 'lib', 'mozilla', 'unsigned', 'nss']


THE TOP 15 WORDS FOR TOPIC #50
['just', 'function', 'build', 'use', 'changed', 'logging', 'line', 'windows', 'json', 'critical', 'mock', 'permissions', 'open', 'main', 'volume']


THE TOP 15 WORDS FOR TOPIC #51
['just', '68', '13', 'instead', '16', 'opera', '10', '11', 'interface', 'image', 'safari', 'end', 'file', 'line', 'chrome']


THE TOP 15 WORDS FOR TOPIC #52
['ev', 'ctrl', 'external', 'problem', 'file', 'page', 'background', 'dns', 'open', 'web', 'attached', 'version', 'store', 'certificate', 'chrome

['src', '15', 'dsym', 'release', 'xcodebuild', 'canary', 'framework', 'browser', 'slave', 'app', 'mac', 'official', 'build', 'google', 'chrome']


THE TOP 15 WORDS FOR TOPIC #94
['add', 'existing', 'cc', 'issue', 'track', 'code', 'currently', 'removed', 'linux', 'aura', 'need', 'bug', 'plugin', 'plugins', 'support']


THE TOP 15 WORDS FOR TOPIC #95
['remove', 'default', 'use', 'config', 'flags', 'portage', 'make', 'work', 'used', 'enable', 'text', '22', 'app', 'disable', 'flag']


THE TOP 15 WORDS FOR TOPIC #96
['run', 'messagepumpforio', 'void', 'dll', 'messagepumpwin', 'browser_sync', 'chromium1', '__thiscall', 'messageloop', 'bytesc', 'httpcache', 'line', 'src', 'base', 'net']


THE TOP 15 WORDS FOR TOPIC #97
['result', 'applicable', 'steps', 'happens', 'reproduce', 'problem', 'fail', 'version', 'safari', 'issue', 'firefox', 'http', 'tested', 'browsers', 'ok']


THE TOP 15 WORDS FOR TOPIC #98
['value', 'chromium', 'gurl', 'ipc', 'uilder', 'valgrind', 'slave', 'int', 'const', 'fun', 

['03', 'code', 'com', 'details', 'show_bug', 'pst', 'comment', 'action', 'attachment', 'cgi', 'https', 'bugs', 'org', 'webkit', 'id']


THE TOP 15 WORDS FOR TOPIC #140
['yahoo', 'chromegw', 'clientsockethandle', 'transaction', 'try', 'thread', 'codereview', 'int', 'run', 'charts', 'steps', 'stumpy_moblab', 'gestures', 'http', 'use']


THE TOP 15 WORDS FOR TOPIC #141
['click', 'build', 'icon', 'step', 'install', 'steps', 'expected', 'menu', 'user', 'version', 'google', 'launcher', '35', 'chrome', 'app']


THE TOP 15 WORDS FOR TOPIC #142
['update', 'user', 'png', 've', 'new', '874', 'browser', 'version', 'entry', 'frame', 'characters', 'windows', 'crash', 'slide', 'chrome']


THE TOP 15 WORDS FOR TOPIC #143
['version', 'problem', 'broken', '35', 'steps', 'seen', 'reproduce', 'popup', 'regression', 'official', 'build', 'issue', 'launch', 'click', 'chrome']


THE TOP 15 WORDS FOR TOPIC #144
['servo', 'need', 'pipe', 'user', 'mouse', '13', 'property', '52', '10', '59', 'lock', 'error', 'ent

In [14]:
dtm.shape

(5000, 12306)

In [15]:
topic_result = LDA.transform(dtm)

In [16]:
topic_result.shape

(5000, 150)

In [17]:
topic_result[0].round(3)

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.889, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.091,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   ,

In [18]:
topic_result[0].argmax()

57

In [19]:
dataset.head()

description
0  Product Version      : <see about:version>URLs...
1  Product Version      : 0.2.149.27 (1583)URLs (...
2  Product Version      : chrome beta 1URLs (if a...
3  Product Version      : 0.2.149.27 (1583)URLs (...
4  Product Version      : 0.2.149.27URLs (if appl...

In [20]:
topic_result.argmax(axis=1)

array([ 57,  97,  57, ...,  80, 126,  80])

In [21]:
dataset['Topic']= topic_result.argmax(axis=1)

In [22]:
dataset.head(10)

description  Topic
0  Product Version      : <see about:version>URLs...     57
1  Product Version      : 0.2.149.27 (1583)URLs (...     97
2  Product Version      : chrome beta 1URLs (if a...     57
3  Product Version      : 0.2.149.27 (1583)URLs (...    126
4  Product Version      : 0.2.149.27URLs (if appl...     34
5  Product Version      : 0.2.149.27URLs (if appl...     97
6  Product Version      : Windows XP 64-bitURLs (...     57
7  Product Version      : 0.2.149.27URLs (if appl...     97
8  Product Version      : <see about:version>URLs...     57
9  This is introduced between 53415 - 53406 (http...     82