In [13]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from nltk.corpus import stopwords
import nltk
import seaborn as sns
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from nltk.stem import PorterStemmer
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, f1_score
import os
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
dataset = pd.read_csv('classifier_data_0.csv', header = 0, encoding= 'utf-8')

dataset.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10'], axis=1, inplace = True)
dataset.fillna("0", inplace = True)

In [14]:
X= dataset['description']
y = dataset['owner']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
X_train.shape

(4000,)

In [15]:
count_vect= CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
print(X_train_counts)

  (0, 32093)	1
  (0, 39709)	1
  (0, 309)	1
  (0, 7071)	1
  (0, 25073)	2
  (0, 14416)	1
  (0, 14285)	1
  (0, 36612)	1
  (0, 40525)	1
  (0, 33527)	1
  (0, 37787)	3
  (0, 31984)	1
  (0, 20474)	1
  (0, 37228)	2
  (0, 22878)	1
  (0, 17124)	1
  (0, 38161)	3
  (0, 40589)	2
  (0, 41120)	2
  (0, 36055)	1
  (0, 37383)	1
  (0, 38537)	1
  (0, 30231)	1
  (0, 26399)	1
  (0, 26228)	1
  :	:
  (3998, 3643)	1
  (3998, 3642)	1
  (3998, 3680)	1
  (3998, 3681)	1
  (3998, 3648)	1
  (3998, 4023)	1
  (3998, 1433)	1
  (3998, 15303)	1
  (3998, 1438)	1
  (3998, 12821)	1
  (3998, 1437)	1
  (3999, 38161)	1
  (3999, 16278)	1
  (3999, 13968)	1
  (3999, 40083)	1
  (3999, 14139)	1
  (3999, 28258)	1
  (3999, 29093)	1
  (3999, 16716)	1
  (3999, 20308)	1
  (3999, 31547)	1
  (3999, 25238)	1
  (3999, 23995)	1
  (3999, 25535)	1
  (3999, 35793)	1


In [4]:
TfIdf_transformer= TfidfTransformer()
X_train_TfIdf = TfIdf_transformer.fit_transform(X_train_counts)

In [5]:
X_train_TfIdf.shape

(4000, 41351)

In [10]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',KNeighborsClassifier(n_neighbors=5)),])
text_clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,

In [11]:
predictions=text_clf.predict(X_test)

In [12]:
print(metrics.confusion_matrix(y_test, predictions))

[[104   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   1   0]
 [  0   0   0 ...   0   0   0]]


In [16]:
print(metrics.classification_report(y_test, predictions))

                             precision    recall  f1-score   support

                          0       0.91      0.54      0.68       192
          a....@samsung.com       0.00      0.00      0.00         0
          a...@chromium.org       0.00      0.00      0.00         3
            aa@chromium.org       0.00      0.00      0.00         4
       aandrey@chromium.org       0.00      0.00      0.00         1
        abarth@chromium.org       0.00      0.00      0.00         2
       aber...@chromium.org       0.00      0.00      0.00         1
      abhis...@synerzip.com       0.00      0.00      0.00         1
       achuith@chromium.org       0.00      0.00      0.00         4
      acolwell@chromium.org       0.00      0.00      0.00         2
         adamk@chromium.org       0.00      0.00      0.00         0
          adlr@chromium.org       0.00      0.00      0.00         3
          ager@chromium.org       0.00      0.00      0.00         1
           agl@chromium.org      

C:\Users\Ohud Raza\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ohud Raza\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
