In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from nltk.corpus import stopwords
import nltk
from sklearn.decomposition import LatentDirichletAllocation
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from nltk.stem import PorterStemmer
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, f1_score
import os
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
dataset = pd.read_csv('classifier_data_20.csv', header = 0, encoding= 'utf-8')

dataset.fillna("0", inplace = True)
dataset.head()

owner                                              title
0      amit@chromium.org  Scrolling with some scroll mice (touchpad, etc...
1       jon@chromium.org  Proxy causes some or all network requests to fail
2  pfeldman@chromium.org  Web inspector button "dock to main window" doe...
3       jon@chromium.org   Habari admin interface is not rendered correctly
4  pkasting@chromium.org      Maximize on second larger monitor not working

In [2]:

dataset['title'] = dataset['title'].apply(lambda x: " ".join(x.lower() for x in str(x).split()))
# Removing punctuation
dataset['title'] = dataset['title'].str.replace('[^\w\s]','')
# Stop word removal
stop = stopwords.words('english')
dataset['title'] = dataset['title'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
#Stemming
st = PorterStemmer()
dataset['title'] = dataset['title'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

X= dataset['title']
y = dataset['owner']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=200)
X_train.shape

(8000,)

In [3]:
text_clf = Pipeline([('vector',CountVectorizer()),('lda',LatentDirichletAllocation(n_components=150, random_state=42)),('clf',KNeighborsClassifier(n_neighbors=5)),])
text_clf.fit(X_train, y_train)

Pipeline(steps=[('vector', CountVectorizer()),
                ('lda',
                 LatentDirichletAllocation(n_components=150, random_state=42)),
                ('clf', KNeighborsClassifier())])

In [4]:
predictions=text_clf.predict(X_test)

In [5]:
print(metrics.confusion_matrix(X_test, predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
print(metrics.classification_report(y_test, predictions))

                                  precision    recall  f1-score   support

               *sjl@chromium.org       0.00      0.00      0.00         0
               a...@chromium.org       0.00      0.00      0.00         7
                 aa@chromium.org       0.04      0.09      0.06        11
            aandrey@chromium.org       0.00      0.00      0.00         2
             abarth@chromium.org       0.05      0.25      0.08         8
            aber...@chromium.org       0.00      0.00      0.00         0
           abhis...@synerzip.com       0.00      0.00      0.00         1
           abodenha@chromium.org       0.00      0.00      0.00         1
           aboxhall@chromium.org       0.00      0.00      0.00         1
            achaulk@chromium.org       0.00      0.00      0.00         1
            achuith@chromium.org       0.00      0.00      0.00         8
           acolwell@chromium.org       0.00      0.00      0.00         1
              adamk@chromium.org     

/home/vector/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/vector/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [7]:
print(metrics.accuracy_score(y_test, predictions))

0.0345
